steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      # This is the only way to pass secrets to the build
      - '--build-arg'
      - 'APP_ENV=$_APP_ENV'
      - '--build-arg'
      - 'ROOT_URL=$_ROOT_URL'
      - '--build-arg'
      - LIFF_ID=$_LIFF_ID'
      - '--build-arg'
      - 'FIREBASE_API_KEY=$_FIREBASE_API_KEY'
      - '--build-arg'
      - 'CHANNEL_ACCESS_TOKEN=$_CHANNEL_ACCESS_TOKEN'
      - '--build-arg'
      - 'CHANNEL_SECRET=$_CHANNEL_SECRET'
      - '--build-arg'
      - 'GA_ID=$_GA_ID'
      - '--build-arg'
      - 'LINE_AUTH_ENDPOINT=$_LINE_AUTH_ENDPOINT'
      - '--build-arg'
      - 'LINE_AUTH_CLIENT_ID=$_LINE_AUTH_CLIENT_ID'
      - '--build-arg'
      - 'LINE_AUTH_CLIENT_SECRET=$_LINE_AUTH_CLIENT_SECRET'
      - '--build-arg'
      - 'FIREBASE_ADMIN_PROJECT_ID=$_FIREBASE_ADMIN_PROJECT_ID'
      - '--build-arg'
      - 'FIREBASE_ADMIN_PRIVATE_KEY_ID=$_FIREBASE_ADMIN_PRIVATE_KEY_ID'
      - '--build-arg'
      - 'FIREBASE_ADMIN_PRIVATE_KEY=$_FIREBASE_ADMIN_PRIVATE_KEY'
      - '--build-arg'
      - 'FIREBASE_ADMIN_CLIENT_EMAIL=$_FIREBASE_ADMIN_CLIENT_EMAIL'
      - '--build-arg'
      - 'FIREBASE_ADMIN_CLIENT_ID=$_FIREBASE_ADMIN_CLIENT_ID'
      - '--build-arg'
      - 'FIREBASE_ADMIN_CLIENT_x509_CERT_URL=$_FIREBASE_ADMIN_CLIENT_X509_CERT_URL'
      - '--build-arg'
      - 'FIREBASE_DB_URL=$_FIREBASE_DB_URL'

      ####
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: qicoka
  _LABELS: gcb-trigger-id=9e1324b6-88ac-40f6-b2db-58a1fc6193c1
  _TRIGGER_ID: 9e1324b6-88ac-40f6-b2db-58a1fc6193c1
  _DEPLOY_REGION: asia-northeast1
  _GCR_HOSTNAME: asia.gcr.io
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - qicoka
