name: CI
on: [push]
jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install packages
        run: yarn install
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build
